site_name: VS Code User Guide
nav:
  - Home: "index.md"
  - Managing Extensions: "pages/extensions.md"
  - Configuring Settings: "pages/settings.md"
  - Starting your first project: "pages/setup.md"
  - Glossary: "pages/glossary.md"
  - Troubleshooting: "pages/troubleshoot.md"


repo_url: https://github.com/aye-ron98/UserGuide

repo_name: aye-ron98/UserGuide

markdown_extensions:
  - admonition

theme:
  name: material
  icon: 
    admonition:
      info: fontawesome/solid/circle-info
      warning: fontawesome/solid/triangle-exclamation
      success: fontawesome/solid/check

  features:
    - navigation.sections
    - navigation.top
    - toc.integrate

    # 404 page
  static_templates:
    - 404.html

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values
  language: en
  

  copyright: Copyright &copy; 2023 - Aron Zhang, Hanxiao Mao